### ISSUE TITLE
Proposal : Interval check for new releases and inform user about update

### ISSUE THREAD

**Issue by wsuphappyhour** [opengs/uashield#102]
As tool is actively developed most of people wont check github again, so it is good to inform about update

**Comment by Razikus** [comment]
already done https://github.com/opengs/uashield/commit/4d809e8e90365e4ed4d13009a9036d8706136856

**Comment by wsuphappyhour** [comment]
@Razikus  is commit on 11ver?

**Comment by wsuphappyhour** [comment]
@Razikus there could be option during install that launch on win start up, as people might forget to launch

**Comment by oleksiisedun** [comment]
This feature is implemented and tested in 0.0.12. The issue can be closed.
