### ISSUE TITLE
Functionality not described

### ISSUE THREAD

**Issue by Sammeeey** [opengs/uashield#110]
Unfortunately one can not read what this repo is about in the README.
If you describe it clearly are welcome to add it to the [awesome-ukraine](https://github.com/Sammeeey/awesome-ukraine) repo.

**Comment by opengs** [comment]
Hey. I know what you are talking about :) We cant add this :D. Please PM me in Discord for more info.

**Comment by opengs** [comment]
Closed due to inactivity
