### ISSUE TITLE
Maybe during install option to launch on system "start up" and also implement on win "system tray icon"

### ISSUE THREAD

**Issue by wsuphappyhour** [opengs/uashield#114]

**Comment by wsuphappyhour** [comment]
Maybe during install option to launch on system "start up" and also implement on win "system tray icon"

**Comment by sepo274** [comment]
[Tray icon support and placeholder for app start on startup](https://github.com/opengs/uashield/pull/130)
this is just a first PR to keep it small and simple for review, right after this one "start on startup" will follow

**Comment by opengs** [comment]
Closing, because PR was merged. Tray icon and "launch on startup" were also implemented.
