### ISSUE TITLE
Proposal: how many machines are attacking at the same time

### ISSUE THREAD

**Issue by ysarri** [opengs/uashield#117]

**Comment by Razikus** [comment]
not implementable without centralizing the software
We can add analytics, but we will never do that, because security of users is also important

**Comment by RasmusOtharKirketerp** [comment]
How about some indications of how mant URL are being attacted pr minut/hour/day from local mashine?

**Comment by AlexShkunov** [comment]
> not implementable without centralizing the software We can add analytics, but we will never do that, because security of users is also important

"without centralizing the software" - to the top. Decentralized software is a key for many aspects.

**Comment by opengs** [comment]
The local statistic was successfully implemented. Global statistic is very hard to implement. We are connected to IT Army and they tried to do this but were instantly DDoSed. https://itarmy.com.ua/check/
