### ISSUE TITLE
Smth wrong with disabling proxy

### ISSUE THREAD

**Issue by d3m0n1c** [opengs/uashield#120]
Using latest 0.0.11 version.
Changing threads count affects using PROXY vs DIRECT.

160 threads, Proxy - disabled = using DIRECT
![image](https://user-images.githubusercontent.com/3995036/156916667-ca4334a8-478a-4a77-98c0-b1d121225a34.png)
1000 threads, Proxy - disabled = using PROXY
![image](https://user-images.githubusercontent.com/3995036/156916753-30c1b79d-a0f5-4153-9768-8b348de8d2a7.png)

**Comment by Razikus** [comment]
When it can't reach direct it will use proxy anyway
This is feature implemented in case of banned direct IP

**Comment by d3m0n1c** [comment]
Ok. But why increasing thread count disabling DIRECTs ? Also I see that a lot of errors comes out in logs.
Currently it behaves unpredictably on my machine.

**Comment by Razikus** [comment]
There is no current posibility to switch completely to NOPROXY
It always try to proxy if direct fails
Increasing thread count is not disabling DIRECT
