### ISSUE TITLE
Не виходить запустити на MacOS

### ISSUE THREAD

**Issue by IIIMadHeadIII** [opengs/uashield#125]
При спробі запустити версію 0.0.11 на MacOS 12.2.1 відображається помилка (скрішот) і програма не стартує. Як вирішити проблему? 

![image](https://user-images.githubusercontent.com/101050304/156925079-dab0c62c-9e98-425d-8eda-2134269e9c93.png)

**Comment by andreyshade** [comment]
Натискаєш ок, потім йдеш в System Preferences -> Security & Privacy. У вкладці General дозволяеш запуск

**Comment by IIIMadHeadIII** [comment]
> Натискаєш ок, потім йдеш в System Preferences -> Security & Privacy. У вкладці General дозволяеш запуск

дякую, допомогло!
