### ISSUE TITLE
Trace/breakpoint trap

### ISSUE THREAD

**Issue by deluko15** [opengs/uashield#126]
Getting the Trace/breakpoint trap error when launching the latest version on a clean Ubuntu 20.04 headless box.

messages from syslog:
kernel: [ 1141.853839] traps: shield[2134] trap int3 ip:55c4aa33efb5 sp:7ffc7ff43d90 error:0 in shield[55c4a959e000+6af0000]
kernel: [ 1154.322937] traps: shield[2157] trap int3 ip:561b13663d83 sp:7ffd53523470 error:0 in shield[561b106d3000+6af0000]
kernel: [ 1163.325970] traps: shield[2158] trap int3 ip:559b87c78fb5 sp:7ffe9f32a550 error:0 in shield[559b86ed8000+6af0000]

**Comment by Razikus** [comment]
Screen or something

**Comment by Razikus** [comment]
Probably you have to add --no-sandbox to the command

**Comment by deluko15** [comment]
> 

![image](https://user-images.githubusercontent.com/21267858/156935781-3a0f1632-1508-4b95-b125-6edb39718a54.png)

-no-sandbox gives me the same output

**Comment by Razikus** [comment]
hmm, what means headless box?

**Comment by deluko15** [comment]
a remote server without desktop environment

**Comment by KarboDuck** [comment]
Same problem on ubuntu server 20.04.

Both on:
- UA-Cyber-SHIELD-0.0.30.AppImage
- shield-0.0.30.tar.gz (extracted)

<img width="513" alt="Screenshot 2022-04-07 at 14 40 59" src="https://user-images.githubusercontent.com/53382906/162190848-7241bc04-44fb-464f-a0e2-ba1ff537396b.png">

**Comment by opengs** [comment]
For server without GUI use ```headless``` or ```docker``` installation. Sorry for late response :(
