### ISSUE TITLE
Додайте інформацію про проксі

### ISSUE THREAD

**Issue by danyildiabin** [opengs/uashield#13]
Варто попереджати користувача що без проксі з'єднання більшість українських провайдерів буде блокувати деякі ресурси, тим самим DDOS буде відбуватись на мережу провайдера, а не на ресурс окупанта.

Наразі програма більше заохочує "сильніше" навантажувати ресурси окупанта відключивши проксі з'єднання.

**Comment by opengs** [comment]
@danyildiabin Дякую за уважність. Якщо запит без проксі блокується, система відразу сама переключається на проксі. Тому ми передбачили цей варіант.

Хотіли там внести цю інформацію на інтерфейс, але певно звичайним користувачам не варто це знати, бо більшість з них не володіє такими поняттями. Наша ціль - включив і не думаєш.

Якщо згідні, то буду закривати. Чи можливо є якісь уточнення?

**Comment by danyildiabin** [comment]
Дізнався що axios сам перевіряє TLS сертифікат і побачив як в коді ці такі випадки передбаченні.
Дякую за пояснення таких рішень.
