### ISSUE TITLE
invalid description for docker section

### ISSUE THREAD

**Issue by constantin-ukr** [opengs/uashield#132]
current description 
![image](https://user-images.githubusercontent.com/10629607/156932586-3ed6d13c-13bc-4014-8ece-0cb64cc844cd.png)

![image](https://user-images.githubusercontent.com/10629607/156932519-c9ac1f8e-fba1-43e4-b926-8d5307449dcf.png)

but I am not sure that should be run with tag latest or master

Which of the command is correct?

docker run -it --rm ghcr.io/opengs/uashield:latest 256 true

docker run -it --rm ghcr.io/opengs/uashield:master 256 true

**Comment by Razikus** [comment]
:latest or :master
0.0.x is always development branch

**Comment by Razikus** [comment]
Will fix

**Comment by Razikus** [comment]
Fixed
