### ISSUE TITLE
Невеличкі помилки орфографічні(підкреслені).

### ISSUE THREAD

**Issue by dendenis82** [opengs/uashield#14]
![fix text](https://user-images.githubusercontent.com/21170174/156258524-de8bd98f-23c7-4a13-91a2-8d6b56cece66.jpg)

**Comment by opengs** [comment]
Спасибі. Будемо поправляти.

P.S. Якщо є бажання поправити - запрошую на pull request

**Comment by Amet13** [comment]
https://github.com/opengs/uashield/pull/20
