### ISSUE TITLE
Feature-request: Отображение ошибок и сигнал о них

### ISSUE THREAD

**Issue by WebManG** [opengs/uashield#146]
Доброго дня!
Спасибо за вашу работу!

Сделайте, пожалуйста, отображение цифры: процент успешных атак за последние 10-30 секунд. Чтобы с одного взгляда было видно, работает ли ВПН или его пора менять.
Также можно добавить опциональный звуковой сигнал (раз в заданное в настройках время) при падении успешности атаки ниже заданного в настройках процента.

**Comment by oleksiisedun** [comment]
Please see https://github.com/opengs/uashield/pull/105.

**Comment by WebManG** [comment]
Thank you!
