### ISSUE TITLE
Please release also x86-64 binaries.

### ISSUE THREAD

**Issue by harryztybetu** [opengs/uashield#152]
Am I missing something, do we lack x86-64 in the releases section?

Docker in my setup is not usable as there is a known bug that interferes with VPN client I am using.

**Comment by opengs** [comment]
There is [UA-Cyber-SHIELD-Setup-0.0.13.exe](https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-Setup-0.0.13.exe) its for 32bit system and for 64bit
