### ISSUE TITLE
v0.0.13 can't be installed on MacOS Monterey (arm64 => M1 CPU)

### ISSUE THREAD

**Issue by su-hs** [opengs/uashield#161]
I was able to install previous versions, including `v0.0.11` (on both Catalina `v10.15.5` and Monterey `v12.1`).

But `v0.0.13` on Monterey does ignore "Open" from Context menu from Applications folder, and suggest me to delete file.
I tried  both executables (sure thing - image unpacked, and file copied to Applications):
- https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13-arm64.dmg as I consider main executable for M1 CPU (arm64)
- https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13.dmg - also tried this, to be sure MAYBE it would work. 

But not - both executables can't be installed/executed anyway:

`0.0.13-arm64.dmg` => 
<img width="270" alt="Screenshot 2022-03-10 at 23 06 01" src="https://user-images.githubusercontent.com/100500001/157765700-ac94a37a-cc38-4e60-93a4-b6ff58dbd81c.png">

`0.0.13.dmg` =>
<img width="327" alt="Screenshot 2022-03-10 at 23 12 28" src="https://user-images.githubusercontent.com/100500001/157765703-3e603758-6cef-4191-8bb3-08e8954e6c2e.png">

PS. Same version `v0.0.13` installed OK on MacOS Catalina, Intel CPU. No warnings. I executed and ran attack for a few minutes.

**BUT**
Then I realized, new process with the name `deleted` in Activity Monitor, somewhere from `/System/Library/MessageTracer/SubmitDiagInfo.default.domains.searchtree` which IS new for my eyes, so then I deleted UA Cyber Shield from Applications, and cleared all cached files to be sure. Restarted Mac, and that process still exists. 

I also have such `deleted` process in Activity Monitor on Monterey MacOS. 

**THEN**, I googled then, and:
- https://forums.macrumors.com/threads/is-my-mac-hacked.2238091/
- https://cruisenew.weebly.com/mac-library-messagetracer-submitdiaginfodefaultdomainssearchtree.html
- https://apple.stackexchange.com/questions/254810/what-is-the-deleted-daemon-in-macos
- https://www.reddit.com/r/MacOS/comments/gn85gl/deleted_process_on_catalina/
and seems to be OK, all Macs have it. Didn't know, never seen it, but looks like related to CacheDelete.

Now @Razikus tell me more :) 

1) Could you confirm, you or someone from your team, or CI pipeline at least, actually executed *.dmg file on MacOS for Intel and M1 CPU?
2) Could you confirm, that process `deleted` IS NOT related to UA Cyber SHIELD? Please.

cc/ @dmpanch ; @denysbutenko

**Comment by o-hreshchuk** [comment]
hi @su-hs, I am not on the M1, but the error you got for https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13.dmg is because of the Mac OS privacy: 
Before clicking on the cancel button of that popup:
- open System Preferences
- go to Security & Privacy
- if needed unlock the possibility to make changes (the lock icon in the right bottom corner)
- click cancel on the popup
- after it the message should appear like that one for Example App, but for the Cyber Shield
![](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/Big-Sur/macos-big-sur-system-prefs-security-general-open-anyway.png)

**Comment by Razikus** [comment]
Yes, x64 for mac was tested
Arm64 for mac wasn't tested, and it looks that it don't work atm, but we can't really check 

This process is unrelated to this software

**Comment by bretsko** [comment]
Can confirm that https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13-arm64.dmg - doesn't work on M1
BUT 
https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13.dmg - works on BOTH

**Comment by Byraktar-kyiv** [comment]
> Can confirm that https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13-arm64.dmg - doesn't work on M1
> BUT
> https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13.dmg - works on BOTH

Same here **Macbook Air M1 macOS Big Sur 11.6.4** 

> https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13-arm64.dmg

**NOT WORKING!**  This version was only for M1 CPU but didn't work 

> https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13.dmg 

**WORKING M1 CPU**
