### ISSUE TITLE
how it is possible without internet connection?

### ISSUE THREAD

**Issue by constantin-ukr** [opengs/uashield#164]
![image](https://user-images.githubusercontent.com/10629607/157823833-223a3dac-bbe6-434b-8334-f2bc3d5fc55d.png)

I lost my internet connection but the program does not show any information about it and continues to increase counter?

Now, are we possibly doing a mental attack?

**Comment by megger-cgfx** [comment]
The program will continue to try to call the websites, but this will not go through, as you can see by the response: "EHOSTUNREACH". I don't know what it stands for exactly, but it's clear that it's unreachable.

**Comment by opengs** [comment]
as @megger-cgfx said :)
