### ISSUE TITLE
Why are you guys not adding targets from IT ARMY of Ukraine?

### ISSUE THREAD

**Issue by hudak0va** [opengs/uashield#166]
Question is in topic name. 
I never see targets from https://t.me/itarmyofukraine2022 in your [targets list](https://github.com/opengs/uashieldtargets/blob/v2/sites.json). Please add targets from that telegram channel on every new message there!

**Comment by hudak0va** [comment]
Or give us ability to add targets ourselves

**Comment by hudak0va** [comment]
@opengs @Muronuch

**Comment by sk146** [comment]
Data with  sites is taken from here https://github.com/opengs/uashieldtargets/blob/v2/sites.json, I think you need to make suggestions there

**Comment by s7aycool** [comment]
Only 6 sites? wtf

**Comment by opengs** [comment]
Group of volunteers are working on targets. You are free to make suggestions. Please discuss this with "spotters" on our discord channel.

Also there are a lot of technical issues. Today they added targets ```91.201.54.26 (21/tcp, 22/tcp, 80/tcp, 443/tcp, 67/udp)
195.10.198.35 (53/tcp, 53/udp, 67/udp)
195.10.198.37 (25/tcp, 53/tcp, 53/udp, 67/udp)
195.10.198.201 (113/tcp, 443/tcp, 500/udp)
195.10.198.242 (25/tcp, 53/tcp, 53/udp)
195.10.198.136 (113/tcp, 443/tcp)
195.10.198.243 (113/tcp, 443/tcp, 500/udp) 
195.10.198.204 (113/tcp, 443/tcp, 500/udp)
195.10.198.130 (22/tcp, 80/tcp, 113/tcp, 4443/tcp)
195.10.198.208 (80/tcp, 113/tcp, 443/tcp, 500/udp)
195.10.198.203 (113/tcp, 500/udp, 520/udp/, 1144/udp)```
But we cant add them. We have big international community. And they will ask us "what we are attacking?"
There a LOT more issue related to targets.

Targets are changed by script every 20 mins. Script is modified by community.
