### ISSUE TITLE
Can't run it, can't build it

### ISSUE THREAD

**Issue by s7aycool** [opengs/uashield#167]
Hello. I am trying to run your soft on Ubuntu 20.14. I downloaded shield-0.0.13-ia32.tar.gz and shield-0.0.13-arm64.tar.gz
![image](https://user-images.githubusercontent.com/59872947/158281450-056b678f-c36b-4bf7-b0d3-cc2235984cf0.png)

Here is what i am getting when I am trying to build:
![image](https://user-images.githubusercontent.com/59872947/158281528-face741e-1439-4cf1-a194-515824e9c4bc.png)

**Comment by opengs** [comment]
are you sure with architecture? also try appimage [UA-Cyber-SHIELD-0.0.13.AppImage](https://github.com/opengs/uashield/releases/download/v0.0.13/UA-Cyber-SHIELD-0.0.13.AppImage)

build error says that you dont have quasar framework. are you installed all dependencies with `npm install`?

**Comment by f1r3w411** [comment]
> Hello. I am trying to run your soft on Ubuntu 20.14. I downloaded shield-0.0.13-ia32.tar.gz and shield-0.0.13-arm64.tar.gz

Hi.
I installed Ubuntu 20.04 on my 6 office PCs, and they are working fine during all these days.
Download shield-0.0.13.tar.gz , unpack it, open the folder containing unpacked files, start terminal there with no root and run `./shield`

**Comment by s7aycool** [comment]
@opengs yes, I downloaded wrong architecture T_T
@f1r3w411 thanks, shield-0.0.13.tar.gz launched just fine
