### ISSUE TITLE
Effectiveness of attack on Cloudflare protected site

### ISSUE THREAD

**Issue by oleksiisedun** [opengs/uashield#172]
I see that app attacking https://www.pravda.ru for many hours. The response is always 403 OK. This site is protected by Cloudflare. 
I am curious about effectiveness of app work for such target (I assume it's useless).

**Comment by ybaidiuk** [comment]
Does somebody have an idea?

**Comment by opengs** [comment]
Its effective when we have enough proxies. We have a lot of successful examples on `targets` channel in our discord community.

https://media.discordapp.net/attachments/948172643989880933/951488160976748624/unknown.png
https://media.discordapp.net/attachments/948172643989880933/950079071738544198/unknown.png?width=1440&height=441

we are working on CF punch through :)

**Comment by oleksiisedun** [comment]
Got it, thanks!
