### ISSUE TITLE
You need buy mobile proxies

### ISSUE THREAD

**Issue by udjfvnsaoepna** [opengs/uashield#174]
You need buy for attack **ru mobile** **_proxies_** with **ip rotation** (by timer, with socks5 support)

Example:
https://mobileproxy.space
https://rsocks.net/en/mobile-proxy
https://onlinesim.ru/en/proxy/

PS. Mobile operators have large ip list

**Comment by s7aycool** [comment]
How often they can change ip's?

**Comment by udjfvnsaoepna** [comment]
> How often they can change ip's?

By timer, 1 min - 5 min
Depends where you bought

**Comment by opengs** [comment]
we are buying :) Check message in our Discord community https://discord.com/channels/947780848898437170/953993364951416852/953997642210353222

They cost a lot :( So we need donations https://github.com/opengs/uashield/blob/master/README-en.md#donations
