### ISSUE TITLE
Зменшити кількість дефолтних воркерів в docker-compose.yml

### ISSUE THREAD

**Issue by bsurai** [opengs/uashield#176]
Зараз в **docker-compose** по дефолту встановлено 256 воркерів. З моїх спостережень для найдешевших віртуальних машин на хмарних сервісах більш оптимальним є 16 воркерів, що часто дозволяє норм працювати навіть  без проксі. Мої колеги дослідним шляхом для себе встановили оптимальну кількість біля 50 воркерів.

**Comment by opengs** [comment]
В новій версії існує алгоритм автоматичного визначення кількості воркерів. Будь ласка оновіться щонайменше до 0.0.16
