### ISSUE TITLE
Release 13. Dont start shield on Kali Linux

### ISSUE THREAD

**Issue by RashVV** [opengs/uashield#179]
Download page from release 13. folder and after start file in unpack folder it is don't start .
So I take 11 version and start processes. Check please amd64 .tg.??

**Comment by opengs** [comment]
please, try to use .Appimage

**Comment by iostreamchik** [comment]
@RashVV you might try to build with [**yarn**](https://classic.yarnpkg.com/lang/en/docs/install/#mac-stable) but not **npm**.
I've successfully compiled the latest 0.0.17 version. Unfortunately, it has a security risk warning so please be strict with your data.

**Comment by opengs** [comment]
Closed due to inactivity. Please create new issue )
