### ISSUE TITLE
Weird DDOS termination

### ISSUE THREAD

**Issue by bsurai** [opengs/uashield#181]
There's a weird case. I see terminated ddosing in a several hours after starting. There're no new requests after that. I've seen it with:
- itguild/uashield   dev:start mode
- opngs/uashield  electron mode
- opngs/uashield  docker-compose mode

I try to investigate it. If you have any idea that would be great.

**Comment by opengs** [comment]
What version do you have?

**Comment by opengs** [comment]
Closed due to inactivity. Please create new issue.
