### ISSUE TITLE
How the attack is performed

### ISSUE THREAD

**Issue by Foresteam** [opengs/uashield#187]
Why not to use hping? On the systems it works on, at least

**Comment by opengs** [comment]
Hi. Sorry, but i dont understand your question. Can you describe problem more clearly?

**Comment by Foresteam** [comment]
It's a suggestion. HPing3 is better for "pen testing" with its raw sockets, as far as I know

**Comment by opengs** [comment]
our tools is working on linux/macos/windows/raspberry pi/arm systems. Thats hard with other tools. Also in new, not released version, we have low level atacks (UDP flood / slowloris / ...). For now we will not change to other backend.
