### ISSUE TITLE
Як стартанути на Macos?

### ISSUE THREAD

**Issue by ross104** [opengs/uashield#19]
<img width="302" alt="Знімок екрана 2022-03-02 о 11 31 22" src="https://user-images.githubusercontent.com/10098863/156334366-2ca2a858-303d-4dbe-a46a-2fb6b2e5cfd0.png">

**Comment by sviatoslav-lebediev** [comment]
стартонути, потім піти подивитись тут 
![image](https://user-images.githubusercontent.com/19693768/156335184-c11af429-c9d8-4f28-be8d-94119551ce05.png)

дозволити запуск

**Comment by ross104** [comment]
Дяк! Затупив :)
