### ISSUE TITLE
Logs in new versions are gone - that's quite unfortunate

### ISSUE THREAD

**Issue by alienalien13** [opengs/uashield#192]
Hi guys, without a log of requests and their status it is not clear whether they succeed or not, which is extremely important - indicates the need to change VPN location.

This issue is a request to return logs.

**Comment by alienalien13** [comment]
reproducible on Windows

**Comment by opengs** [comment]
To understand logs you must know what is 200/400/500/timeout statuses. We are focused on users, that dont know about this. And there where a lot of questions like "what is 200? everything ok?". So we added this efficiency status bar, where 200/400/500 is ok and every other status is bad. Efficiency bar shows information about last 2k requests.

We understand, that for more advanced users like you - this is bad :(.

Logs where moved to terminal. Just start program from terminal and they will be here - in terminal window :)

Let us know if this is ok for you or you have other suggestions. If ok - I will close issue :)

**Comment by alienalien13** [comment]
Ooh alright, I see now. Thought efficiency bar is about parallelism. Thanks!

Maybe makes sence to add some tooltip there with a comment what does it mean? I might be not the only one, hopefully 😄😄

**Comment by kotenok2000** [comment]
You can run program with this bat file.
:run
"C:\Users\username\AppData\Local\Programs\shield\UA Cyber SHIELD.exe"
pause
goto :run

**Comment by opengs** [comment]
We where discussing this internally `Maybe makes sence to add some tooltip there with a comment what does it mean?`. UI stays the same. Problem with logs solved.
