### ISSUE TITLE
Please, delete this time line, or add mode --no-time

### ISSUE THREAD

**Issue by BogdanDevUA** [opengs/uashield#195]
![Screenshot_24](https://user-images.githubusercontent.com/81070564/160096353-e57a58ad-cd5c-46b0-b1b0-f5bd0b8a8edc.png)

**Comment by opengs** [comment]
![image](https://user-images.githubusercontent.com/34212339/162594039-d517c2e6-d46c-4122-991e-105d3e4c1e3c.png)
Help from version 0.0.31
