### ISSUE TITLE
It's even legal?

### ISSUE THREAD

**Issue by BlitGaming** [opengs/uashield#199]
This software is designed to harm the sites of the Russian Federation, but at the beginning of the file README.md it is said that "This software is created for educational purposes and you should use it only on your own website."

What the hell?

**Comment by barateza** [comment]
Tell me one international law that prevents anyone from running this software. There isn`t any.

If your country prevents you from doing so, be a good law-abiding citizen and don't use it. Simple as that.

**Comment by opengs** [comment]
Creating software is 100% legal. Its on yours responsibility how you use it and what are you doing with it.

We are providing software "as is". If its not legal in your county, you should not use it. Same with other popular software like MHDDoS, LOIC, .... - they also can be used "... to harm the sites of the Russian Federation"
