### ISSUE TITLE
Issue with proxy on Raspberry Pi device

### ISSUE THREAD

**Issue by andreyshade** [opengs/uashield#202]
After some time of work I have got errors in logs: 
<img width="359" alt="image" src="https://user-images.githubusercontent.com/10078161/161424609-0fa46b58-8909-4cf8-81e3-f1601be30f2b.png">
Any idea how to fix this?

**Comment by opengs** [comment]
Hm. Maybe github/gitlab page returned bad code. Did it fixed after 10-15 minutes (proxy update interval) ?

**Comment by andreyshade** [comment]
It works properly now after this issue happened 5 hors ago. I will check later log output and updated this topic

**Comment by opengs** [comment]
In new update it will be ok :) . Now it is not deleting existing proxy list if it cant load new one.

Fix will be in 0.0.24 or 0.0.25. I will close issue when there will be release

**Comment by opengs** [comment]
Fixed
