### ISSUE TITLE
QUIT LYING AND ADMIT IT: THIS IS ILLEGAL AND DESTRUCTIVE AS HELL

### ISSUE THREAD

**Issue by maximxlss** [opengs/uashield#203]
This is NOT pro-ukraine, this is anti-russian and straight up illegal.

**Comment by opengs** [comment]
Its 100% legal. We are just tool. Like repositories:
https://github.com/NewEraCracker/LOIC
https://github.com/MatrixTM/MHDDoS
https://github.com/Ha3MrX/DDos-Attack
https://github.com/palahsu/DDoS-Ripper
Or hundreds of others.

If you have a hummer - its YOUR choice how to use it.
We are NOT saying how you should use it.
And we are NOT responsible how you will use it.
