### ISSUE TITLE
як переконатися, що Deploy attacker on your Raspberry Pi! працює справно?

### ISSUE THREAD

**Issue by Avinamor** [opengs/uashield#21]

**Comment by Razikus** [comment]
Hi, sorry that in EN
All you need is to deploy it on balena cloud, wait for release to end build, and add more devices

Follow mp4s

https://user-images.githubusercontent.com/12664801/156373276-7a1642c6-b74e-409b-b1c6-f8b794163eff.mp4

https://user-images.githubusercontent.com/12664801/156373286-82af3c62-337a-4fd5-8d89-f84e3eb91ba6.mp4

https://user-images.githubusercontent.com/12664801/156373304-98f36a4d-0d43-452b-8e49-9dd2d6315960.mp4

I will post another video when download on the device ends

**Comment by Avinamor** [comment]
thanks a lot for the video!

**Comment by Razikus** [comment]
No problem, it now supports also RPI Zero, so all embedded should works in this case

I will close this issue
