### ISSUE TITLE
Заблочені акаунти на Linode та Digital Ocean

### ISSUE THREAD

**Issue by bsurai** [opengs/uashield#212]
2 хмарні сервіси заблочили акаунти після тривалого використання. Можливо через роботу з параметром `useOnlyProxy = false` або через завелике навантаження на машинках, точної причини назвати не можу.

**Comment by opengs** [comment]
Так. Тому треба брати свіжі. Можете ще також написати в техпідтримку, або запитати що робити в комюніті (найкраще на діскорді) - думаю з таким точно вже стикалися і певно знають що робити. Блокувати будуть
