### ISSUE TITLE
Питання

### ISSUE THREAD

**Issue by BogdanDevUA** [opengs/uashield#213]
Чому коли я запускаю uashield в google cloud shell і виходжу з сайту на 5 хвилин, атака працює, але приблизно через пів години атака не йде, процес вбивається, що треба робити? (screen теж пробував)

**Comment by opengs** [comment]
Блокують IP певно. Або google це бачить і не дозволяє. Що робити незнаю, ми цей варіант офіційно не підтримуємо - все що на нього є це від комюніті.
