### ISSUE TITLE
[Suggestion] Implement this DDOS strategy?

### ISSUE THREAD

**Issue by rodrigograca31** [opengs/uashield#214]
Hi.

The new version has multiple "features".
I suggest we add this: [https://www.hackers-arise.com/post/clogging-and-dosing-russia-s-internet-with-zmap](https://www.hackers-arise.com/post/clogging-and-dosing-russia-s-internet-with-zmap)

It runs a `zmap` command with a random source IP and against a Russia based IP.
There's also a [list of all Russian IPs at the bottom](https://lite.ip2location.com/russian-federation-ip-address-ranges) which could be incorporated into UA Cyber Shield.
It would pick a random Russian IP and attack it.

**Comment by opengs** [comment]
Hi,
we have to check the attack algorithm of the zmap. I think they are using a basic TCP/UDP flood. UDP is already implemented in the app.

**Comment by rodrigograca31** [comment]
Ok. I havent read the code but I assumed the app just did basic HTTP requests....
Good to know its more advanced than that!

**Comment by opengs** [comment]
Ok. I checked this. Unfortunately, it will be very hard to do because we still have to support 3 platforms (Linux, Windows, Mac) on x32/x64/arm/... . And this app is in C language so it will be too difficult to integrate and very hard to maintain.
