### ISSUE TITLE
проблеми з інтернетом

### ISSUE THREAD

**Issue by Rothschildiuk** [opengs/uashield#215]
Коли запускаю програму то у мене виникають проблеми з інтернетом, інтернет працює дуже погано не завантажуються сайти, та фото/відео в телеграм і т.д.
Комп підключений до інтернету через wifi, чи буде ситуація краща якщо під'єднати його через ethernet?

**Comment by opengs** [comment]
Ну так в цьому суть проги :) Вона старається весь інтернет по максимуму вижрати.

В вкладці DDoS виберіть ручний режим і встановіть кільтіксь потоків на 16 наприклад. Тоді буде менше інтернету викоритовувати.
