### ISSUE TITLE
Косметичний бак: Ранг не відповідає статистиці після обнови

### ISSUE THREAD

**Issue by Shpigorx** [opengs/uashield#219]
На 1.0.6 змінилась таблиця статистики і поплив ранг.

26М відповідає Pickled cucumber :D

![image](https://user-images.githubusercontent.com/12695405/165110317-05ed2f12-aa61-4b39-a20a-3c7e2e38ba32.png)

**Comment by opengs** [comment]
Так, там тільки ефективні атаки враховуються. Пофікшу в наступній версії

**Comment by opengs** [comment]
В версії 1.0.7 вказана кількість ефективних атак то тепер відповідає.
