### ISSUE TITLE
Додайте відображення кількості підключених пристроїв

### ISSUE THREAD

**Issue by koreyba** [opengs/uashield#22]
Буде чудово бачити скільки людей (чи пристроїв) разом наносять кібер атаки, це б надихало. Думаю, що це не важко додати.

**Comment by opengs** [comment]
Для цього треба сервер моніторингу. Сервер можуть положити досом противники. Будемо думати чи зможемо щось зробити

**Comment by opengs** [comment]
Є Google Analytics. Час від часу дані кидаємо в чат. на рахунок їх виписування будемо думати
