### ISSUE TITLE
Writing mistake in the title in rating (UA language)

### ISSUE THREAD

**Issue by projectok92** [opengs/uashield#221]
In Ukrainian "Ющенк**а**" should be here.

<img width="600" alt="Знімок екрана 2022-04-29 о 19 10 37" src="https://user-images.githubusercontent.com/58164186/165983472-6dd20569-46c8-44df-8a6b-e8eb2e8c46c0.png">

**Comment by rodrigograca31** [comment]
https://github.com/opengs/uashield/blob/18301f3750c0f11c5a63e68d6ba0eeb3a29dbc8c/src/i18n/ua-ua/index.ts#L128

Send a PR? 🤔
I dont know the language....

**Comment by projectok92** [comment]
https://github.com/opengs/uashield/blob/18301f3750c0f11c5a63e68d6ba0eeb3a29dbc8c/src/i18n/ua-ua/index.ts#L128

It should be:
` 5: 'Бджоли Ющенка', `

Just the very last letter is 'а'

**Comment by opengs** [comment]
cool issue :D I will fix this in next release

**Comment by opengs** [comment]
Fixed in 1.0.10
