### ISSUE TITLE
Docker container life time is always short (few seconds - less than hour)

### ISSUE THREAD

**Issue by artempolikarpov** [opengs/uashield#222]
Hi!

I've downloaded and executed `azure-custom-data-script.sh` on ubuntu machine. 
But when I get logs from running container I always see short life time of the container (from few seconds to 30 minutes)
When I get the logs I see almost same picture:
`Automatic planer changed workers count from [29] to [28]
2022-05-03T17:08:42.082Z | HTTP | https://*** | DOWN OR BLOCKED
2022-05-03T17:08:42.401Z | HTTP | https://*** | DOWN OR BLOCKED
2022-05-03T17:08:42.766Z | HTTP | https://*** | DOWN OR BLOCKED
`

Docker is installed.

Is it ok or not?

**Comment by opengs** [comment]
Hi @artempolikarpov, sorry for the late response. By lifetime you mean, that container restarts? Because logs are good.

**Comment by artempolikarpov** [comment]
Hi @opengs yes, restarting of the container is it ok?

**Comment by opengs** [comment]
There was a bug in the script. Fixed with c26c5cd75ac0e1136ad448234084276f5073cfbb . Now it should restart every 2h. You have to manually modify `/home/cronjob` or recreate vm.

**Comment by opengs** [comment]
Also, @artempolikarpov thank you for pointing this out.
