### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by BogdanDevUA** [opengs/uashield#226]
Тут якась помилка
![Screenshot_87](https://user-images.githubusercontent.com/81070564/174230889-822a3b92-afe8-48be-a595-cd98cc149817.png)
![Screenshot_88](https://user-images.githubusercontent.com/81070564/174423352-c476b11f-6f6b-443e-a88c-84b020d32a12.png)
![Screenshot_89](https://user-images.githubusercontent.com/81070564/174423356-ffabc5c3-757a-47df-9069-947824a98324.png)

**Comment by opengs** [comment]
Привіт. Від цього прога лягає, чи ні? Це може бути проблема в GoogleAnalytics. То там не пофіксити ((

**Comment by BogdanDevUA** [comment]
> Привіт. Від цього прога лягає, чи ні? Це може бути проблема в GoogleAnalytics. То там не пофіксити ((

Від цього прога не лагає
Може спробуєте замінити Google Analytic Key ?
