### ISSUE TITLE
Додайте статистику повалених сайтів

### ISSUE THREAD

**Issue by koreyba** [opengs/uashield#23]
Для бойового кібер духу було б дуже класно, аби ті сайти, які впали, відображались десь як "успішні атаки" чи щось таке.

**Comment by Nazar356** [comment]
+++++++++++++++++++

**Comment by Y0r** [comment]
Перша пачка цілей вже добавлена
https://stats.uptimerobot.com/gVXj8tq56E

пароль: ua_shield

Працюю над другою

**Comment by Y0r** [comment]
Додатково скидаю статус основних цілей
https://stats.uptimerobot.com/p67OJf9E77

пароль: RussiaSucks

**Comment by opengs** [comment]
@Y0r Нажаль ці рішення не будуть працювати. Ворог блокує IP поза Росіює/Білорусю, тому дані не актуальні. Для цього ми робили внутрішню розробку яка працює на серверах в Москві. Результати по цілям постійно стараємося кидади в Discord

Те що впало, ведемо в Discord. Які ще ж пропозиції @koreyba ?

**Comment by opengs** [comment]
Ми повністю інтегровані з IT Army і є одним з офіційних інструментів. Вся статистика тут https://itarmy.com.ua/check/ . Також офіційний телеграм канал https://t.me/itarmyofukraine2022
