### ISSUE TITLE
docker build faild

### ISSUE THREAD

**Issue by constantin-ukr** [opengs/uashield#27]
D:\Projects\learning\uashield>docker build -t uashield .
[+] Building 12.3s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => ERROR [internal] load metadata for docker.io/library/node:14-alpine                                           12.2s
 => [auth] library/node:pull token for registry-1.docker.io                                                        0.0s
------
 > [internal] load metadata for docker.io/library/node:14-alpine:
[+] Building 25.0s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0sk
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
[+] Building 25.8s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
[+] Building 25.9s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
[+] Building 26.1s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
[+] Building 26.4s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
[+] Building 27.5s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
[+] Building 27.8s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
[+] Building 28.2s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
[+] Building 36.2s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
[+] Building 36.3s (9/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
[+] Building 68.2s (9/12)
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:14-alpine                                                 13.1s
 => [auth] library/node:pull token for registry-1.docker.io                                                        0.0s
[+] Building 68.8s (9/12)
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:14-alpine                                                 13.1s
 => [auth] library/node:pull token for registry-1.docker.io                                                        0.0s
[+] Building 71.0s (10/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:14-alpine                                                 13.1s
 => [auth] library/node:pull token for registry-1.docker.io                                                        0.0s
 => [1/7] FROM docker.io/library/node:14-alpine@sha256:9a2aa545388a135b496bd55cef2be920b96c4526c99c140170e05a8de3  6.6s
 => => resolve docker.io/library/node:14-alpine@sha256:9a2aa545388a135b496bd55cef2be920b96c4526c99c140170e05a8de3  0.0s
 => => sha256:f0b94cdce0f39cf2853c3ebedbd1696e64f31f6854918e4672ef5f92099dc9e1 2.36MB / 2.36MB                     1.1s
 => => sha256:664688b94c1580623bcd4a54c20448eaf12b1da320e8f714fda094ed2faacd85 451B / 451B                         0.6s
 => => sha256:9a2aa545388a135b496bd55cef2be920b96c4526c99c140170e05a8de3fce653 1.43kB / 1.43kB                     0.0s
 => => sha256:43ec2ba01c2a245e341489956258afd3535a9ebfdf87ade04b84299ca736607f 1.16kB / 1.16kB                     0.0s
 => => sha256:755b96824e405a4849d187efc06dfd2d95478d35719f956dff1a01bba4b3096c 6.53kB / 6.53kB                     0.0s
 => => sha256:39aa0d19fbe176d43dbe68edc8bb108983b40c55ef6b9f759360b3f5bacf418f 37.13MB / 37.13MB                   2.8s
 => => extracting sha256:39aa0d19fbe176d43dbe68edc8bb108983b40c55ef6b9f759360b3f5bacf418f                          3.0s
 => => extracting sha256:f0b94cdce0f39cf2853c3ebedbd1696e64f31f6854918e4672ef5f92099dc9e1                          0.2s
 => => extracting sha256:664688b94c1580623bcd4a54c20448eaf12b1da320e8f714fda094ed2faacd85                          0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 1.46MB                                                                                0.1s
 => [2/7] RUN mkdir -p /code                                                                                       0.9s
 => [3/7] WORKDIR /code                                                                                            0.0s
 => [4/7] COPY package.json yarn.lock /code/                                                                       0.1s
 => ERROR [5/7] RUN yarn install                                                                                  50.1s
------
 > [5/7] RUN yarn install:
#9 0.893 yarn install v1.22.17
#9 1.090 [1/5] Validating package.json...
#9 1.096 [2/5] Resolving packages...
#9 2.011 [3/5] Fetching packages...
#9 26.44 error An unexpected error occurred: "https://registry.yarnpkg.com/combined-stream/-/combined-stream-1.0.8.tgz: connect ECONNREFUSED 104.16.27.35:443".
#9 26.44 info If you think this is a bug, please open a bug report with the information provided in "/code/yarn-error.log".
#9 26.44 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install]: exit code: 1

[+] Building 71.4s (10/12)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 34B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/node:14-alpine                                                 30.7s
 => [auth] library/node:pull token for registry-1.docker.io                                                        0.0s
 => [1/7] FROM docker.io/library/node:14-alpine@sha256:9a2aa545388a135b496bd55cef2be920b96c4526c99c140170e05a8de3  0.0s
 => [internal] load build context                                                                                  0.1s
 => => transferring context: 3.83kB                                                                                0.1s
 => CACHED [2/7] RUN mkdir -p /code                                                                                0.0s
 => CACHED [3/7] WORKDIR /code                                                                                     0.0s
 => CACHED [4/7] COPY package.json yarn.lock /code/                                                                0.0s
 => ERROR [5/7] RUN yarn install                                                                                  40.5s
------
 > [5/7] RUN yarn install:
#10 0.885 yarn install v1.22.17
#10 1.083 [1/5] Validating package.json...
#10 1.090 [2/5] Resolving packages...
#10 2.008 [3/5] Fetching packages...
#10 23.32 error An unexpected error occurred: "https://registry.yarnpkg.com/@types/node/-/node-17.0.21.tgz: connect ECONNREFUSED 104.16.27.35:443".
#10 23.32 info If you think this is a bug, please open a bug report with the information provided in "/code/yarn-error.log".
#10 23.32 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install]: exit code: 1

**Comment by constantin-ukr** [comment]
yes, it is Win10 x64 19044.1526

**Comment by constantin-ukr** [comment]
please leaves a link on the main page

**Comment by Razikus** [comment]
Now you can just download image, and it should work without any problems
ghcr.io/opengs/uashield:latest
https://github.com/opengs/uashield/pkgs/container/uashield

**Comment by Razikus** [comment]
It should work now for 100%

**Comment by constantin-ukr** [comment]
thank you so much
