### ISSUE TITLE
Simplify macOS installation

### ISSUE THREAD

**Issue by NSGolova** [opengs/uashield#33]
You can greatly simplify the installation process on macOS by signing and notarising the app. It will be launching with no warnings and no need for system settings changes. Grab the certificates on https://developer.apple.com (you need to register and it will cost 100 bucks) or I can sign and notarise builds for you, but it will expose me as the signer.

**Comment by Razikus** [comment]
Hard to achieve unfortunately
If you can sign it for yourself that would be awesome, but you are then more or less responsible for this software

Also you would have to trust us and send us your private keys to achieve signing in github actions

**Comment by opengs** [comment]
Probably, problem will not be resolved. We cant add our own key and no one wants)) Also key can be banned by Apple. We where searching for month. Closing issue, because we dont see a solution
