### ISSUE TITLE
Should I use any VPN to protect myself?

### ISSUE THREAD

**Issue by oleslav** [opengs/uashield#35]
Should I use any VPN to protect myself? Or is there no need to do this?

**Comment by koreyba** [comment]
There is no need in this if you switch on "User proxy" toggle. 
But actually it doesn't work well (meaning attacks don't actually happen), so VPN is better (then switch off proxy)
Free VPN https://onlineshop.f-secure.com/789/purl-free-freedome-for-ukraine

**Comment by opengs** [comment]
Agree with @koreyba . We are trying to change proxy but if you want more results - VPN, without VPN its still ok :)

**Comment by oleslav** [comment]
Thank you a lot for your answers :D
