### ISSUE TITLE
Можливість оновлюти чи змінювати списки хостів.

### ISSUE THREAD

**Issue by iRaunchy** [opengs/uashield#37]
Бачу що гоняє тиж самі списку, сайти вже лежать.
Як перемкнутись на щось інше? Можливо якось координуватись з іншими сотами? Є кілька каналів в ТГ, що надає цілі. Можу скинути в лічку десь.

**Comment by mlytvyn** [comment]
@iRaunchy , перелік сайтів оновлюються автоматично з https://raw.githubusercontent.com/opengs/uashieldtargets/master/sites.json, зміст якого змінюється відповідно до поточних пріорітетів.
якщо в вас є пропозиції відносно додаткових сайтів - пишить в discord - https://discord.com/channels/947780848898437170/948172643989880933

**Comment by iRaunchy** [comment]
https://ai-bank.ru/ | ERR_SOCKET_CLOSED
https://bcs-bank.com/ | ERR_SOCKET_CLOSED
https://www.round.ru/ | ERR_SOCKET_CLOSED
https://rubistar.by | ERR_SOCKET_CLOSED
https://globusbank.com.ua/ru.html | ERR_SOCKET_CLOSED
https://bcs-bank.com/ | ERR_SOCKET_CLOSED
https://www.kremlinbank.ru/ | ERR_SOCKET_CLOSED
https://ai-bank.ru/ | ERR_SOCKET_CLOSED
https://globusbank.com.ua/ru.html | ECONNABORTED
https://bcs-bank.com/ | ERR_SOCKET_CLOSED
https://aversbank.ru/ | ERR_SOCKET_CLOSED
https://www.round.ru/ | ERR_SOCKET_CLOSED
https://globusbank.com.ua/ru.html | ERR_SOCKET_CLOSED
https://ai-bank.ru/ | ERR_SOCKET_CLOSED
https://www.kremlinbank.ru/ | ERR_SOCKET_CLOSED
https://bbr.ru/ | ECONNABORTED
http://www.altynbank.com/ | ECONNABORTED
https://globusbank.com.ua/ru.html | ERR_SOCKET_CLOSED
https://aversbank.ru/ | ERR_SOCKET_CLOSED
https://ai-bank.ru/ | ERR_SOCKET_CLOSED
https://abakan.aero/ | ECONNABORTED
https://aversbank.ru/ | ERR_SOCKET_CLOSED
https://www.kremlinbank.ru/ | ECONNABORTED
https://globusbank.com.ua/ru.html | ERR_SOCKET_CLOSED
https://ai-bank.ru/ | ERR_SOCKET_CLOSED
https://aversbank.ru/ | ERR_SOCKET_CLOSED
https://globusbank.com.ua/ru.html | ERR_SOCKET_CLOSED
https://ai-bank.ru/ | ERR_SOCKET_CLOSED
https://www.bspb.ru/ | DIRECT | 200
https://aversbank.ru/ | ERR_SOCKET_CLOSED
https://www.akibank.ru/ | DIRECT | 200
https://ai-bank.ru/ | ERR_SOCKET_CLOSED
https://www.bm-bank.ru/ | ECONNABORTED
https://www.bspb.ru/ | DIRECT | 200
https://www.akibank.ru/ | DIRECT | 503
https://www.bankperm.ru/ | DIRECT | 200
https://www.gorbank.spb.ru/ | DIRECT | 200
https://www.akibank.ru/ | DIRECT | 200
https://www.bankperm.ru/ | DIRECT | 200
https://www.akibank.ru/ | DIRECT | 200
https://www.bankperm.ru/ | DIRECT | 200
https://www.gorbank.spb.ru/ | DIRECT | 200
https://www.akibank.ru/ | DIRECT | 200
https://www.bspb.ru/ | DIRECT | 200
https://www.vtb.ru/ | ERR_SOCKET_CLOSED
https://www.gorbank.spb.ru/ | DIRECT | 200
https://www.vtb.ru/ | ERR_SOCKET_CLOSED
https://www.bankperm.ru/ | DIRECT | 200
https://acs7.sbrf.ru/ | ECONNABORTED
https://www.vtb.ru/ | ERR_SOCKET_CLOSED
https://www.bspb.ru/ | DIRECT | 200
https://www.vtb.ru/ | ERR_SOCKET_CLOSED
https://www.bankperm.ru/ | DIRECT | 200
https://abakan.aero/ | ERR_SOCKET_CLOSED
https://www.round.ru/ | ECONNABORTED
https://abakan.aero/ | ERR_SOCKET_CLOSED
https://acs3.sbrf.ru/ | ECONNABORTED
https://www.bankperm.ru/ | DIRECT | 200
https://www.gazprombank.ru | ECONNABORTED
https://abakan.aero/ | ERR_SOCKET_CLOSED
https://www.gorbank.spb.ru/ | DIRECT | 200
https://www.bm-bank.ru/ | DIRECT | 502
https://www.bm-bank.ru/ | DIRECT | 502
http://www.bstbank.ru/ | ECONNABORTED
https://www.bm-bank.ru/ | DIRECT | 502
https://www.bm-bank.ru/ | DIRECT | 502
https://www.bankperm.ru/ | DIRECT | 200
https://www.bspb.ru/ | DIRECT | 200
https://bankvl.ru/ | ERR_SOCKET_CLOSED
https://flystw.com | ECONNABORTED
https://bankvl.ru/ | ERR_SOCKET_CLOSED
https://www.gorbank.spb.ru/ | DIRECT | 200
http://alternatio.org/ | ECONNABORTED
https://bankvl.ru/ | ERR_SOCKET_CLOSED
https://acs4.sbrf.ru/ | ERR_SOCKET_CLOSED
https://bankvl.ru/ | ERR_SOCKET_CLOSED
https://www.bm-bank.ru/ | ECONNABORTED
https://www.bystrobank.ru/ | ECONNABORTED

А в чому може бути проблема?
![image](https://user-images.githubusercontent.com/4039149/156443478-8ae82b82-cfb8-4a60-98d8-dcd198077e47.png)

**Comment by iRaunchy** [comment]
Більшість ERR_SOCKET_CLOSED, хоча деякі пробиваються - 200

**Comment by Sergdan1992** [comment]
Програма сама оновлює список цілей? Чи завжди треба перезапускати? Якщо немає автооновленя, треба добавити!

**Comment by mlytvyn** [comment]
> Більшість ERR_SOCKET_CLOSED, хоча деякі пробиваються - 200

- https://github.com/opengs/uashield/issues/38



> Програма сама оновлює список цілей? Чи завжди треба перезапускати? Якщо немає автооновленя, треба добавити!

так, оновлює сама, перезапускати не треба. періодично можете перевіряти доступність нової версії в релізах

**Comment by element100500** [comment]
Додайте будь ласка в список хостів, кремлівський рупор пропаганди https://eadaily.com/

**Comment by easysugar** [comment]
Також хотілося б мати можливість підставляти свій список хостів. Запускаю з докера і було б чудово перевизначати sitesUrl в src-worker/types.ts. Можу спробувати створити інший докер імедж, якщо ніхто не візьметься.

**Comment by bsurai** [comment]
Як щодо розважальних сайтів?
trinixy.ru - на цьому сайтіі сидить багато руснявих ватників. спершу вони пропагували військову міць рашки. тепер намагаються не помічати, що є війна.

**Comment by opengs** [comment]
Сорі за довгу відповідь. Відписуюсь тут, що знали, що ми працюємо над цим, але це не є в приорітеті :) 
Добра оцінка дій наразі тут https://github.com/opengs/uashield/issues/37#issuecomment-1057296705

**Comment by opengs** [comment]
Тепер у нас повна інтеграція з IT Army і ми є одним з офіційних інструментів. Для перевірки цілей заходьте сюди https://itarmy.com.ua/check/ , там також є механізми для пропозицій. Додавання своїх локальних списків в програму покищо не передбачене і маловірогідно що буде додане.
