### ISSUE TITLE
dynamic targets to ddos

### ISSUE THREAD

**Issue by Yneth** [opengs/uashield#39]
I have created an API, it can be updated if needed, currently contains url and priority
http://164.92.247.88:9300/victims

working on adding ip

**Comment by opengs** [comment]
Sorry. In war times we only supporting official data and our own API. Our targets are dynamic.

**Comment by Yneth** [comment]
I can give access to the source code, right now it shows targets with cloudflare flags and ips, the lattest is broken a bit, will fix tomorrow.

Anyway, I am free to support and willing to help. DM me in telegram if needed (I have the same nickname there)

**Comment by Yneth** [comment]
@opengs 
does not really look dynamic at all
https://github.com/opengs/uashield/blob/master/src-worker/doser.ts#L117
