### ISSUE TITLE
Translate UI

### ISSUE THREAD

**Issue by sepastian** [opengs/uashield#4]
~Where do I start?~

~I can offer German, English, Swedish translations. I don't speak Ukranian though.~

Just realized there are other languages. But the default UI is Ukranian and its not obvious to find out how to switch the language.

**Comment by opengs** [comment]
Hej. Thank for you issue. Maybe we will try to check system language and change GUI on the start. We will see what we can do with this.

**Comment by sepastian** [comment]
Instead of using a dropdown menu, just display the flags next to each other?

That would make it much clearer.

**Comment by opengs** [comment]
ah. we have bug on release version. its not displaying flags. we are working on this :)

**Comment by opengs** [comment]
Icons already merged. Will be released in new release.

**Comment by AnriEU** [comment]
Please set English as default language.
I can translate to Czech language and I can record video manuals on English and Czech language.

**Comment by PawFV** [comment]
> e version. its not displaying flags. we are working on this :)

Can you mention / link PR for this?

**Comment by Razikus** [comment]
Fixed by #30
