### ISSUE TITLE
It attacks only help-ukraine-win.com

### ISSUE THREAD

**Issue by sert1m** [opengs/uashield#47]
![Selection_017](https://user-images.githubusercontent.com/10668688/156437212-db8ccd72-4f69-4347-9b39-158f66b9e375.png)

Today it attacks only this site, but previously it was may russians sites.

**Comment by dr-Fade** [comment]
Same issue here, on all active devices. I guess the coordination server has been hacked or smth.

**Comment by Nazar356** [comment]
Yeah, I have the same issue!

**Comment by Amet13** [comment]
Related to this change: https://github.com/opengs/uashieldtargets/commit/f315f20bc546297b29c8d488d0c81af84b2519f4
@Razikus

**Comment by Razikus** [comment]
Hey, we just want to make a little metric and check how powerful community we are

We bomb this website in 30 seconds and we can now tell you how much active users we have
Soon targets will change to proper one

**Comment by dr-Fade** [comment]
> Hey, we just want to make a little metric and check how powerful community we are

Doesn't seem terribly appropriate considering the current situation.

**Comment by Razikus** [comment]
Yep, maybe it was bad idea, and we should attack some other named website
Sorry for that, but it was mainly done for higher our morales later

results will be in one hour

**Comment by RasmusOtharKirketerp** [comment]
Remeber the meassurement will diviate because manu closed the program when they saw it attacked it selves :)

**Comment by RasmusOtharKirketerp** [comment]
I will like to help translate to Danish?

**Comment by Razikus** [comment]
sure, why not - just for the repository and make a pull request

https://github.com/opengs/uashield/tree/0.0.x/src/i18n

**Comment by Razikus** [comment]
Thank you again for participation. 
![unknown](https://user-images.githubusercontent.com/12664801/156458357-03f8f58d-2942-42ee-a59a-855f6968118c.png)

![unknown (1)](https://user-images.githubusercontent.com/12664801/156458366-7592e0f2-12f4-42a2-9a71-cf19bec1f3a8.png)

We have real power to fuck the invader a little!
