### ISSUE TITLE
add random string to attacked url to bypass caches

### ISSUE THREAD

**Issue by mieszkomalawski** [opengs/uashield#50]
as in topic - this will increase load on target app

**Comment by sunflowerdawn** [comment]
Are you thinking just a random query string or something appended to the end? (i.e. `http://some.target/file.html?r=r4nD0mStr1nG`)

**Comment by mieszkomalawski** [comment]
> Are you thinking just a random query string or something appended to the end? (i.e. `http://some.target/file.html?r=r4nD0mStr1nG`)

Yes. Caches like eg. Varnish generate cache keys based on url so adding random query string would bypass cache

**Comment by Razikus** [comment]
we must think about - cause it can goes in other direction
they will just ban requests with param on the sites where it should not have any params for example

**Comment by furiosae** [comment]
> we must think about - cause it can goes in other direction
> they will just ban requests with param on the sites where it should not have any params for example

This is true. Perhaps we split the difference and also randomize when random params and values are added to the end of the URL?

I was also thinking about it earlier, we'd certainly want to randomize the query param name as well as the value--both length and string values.

**Comment by opengs** [comment]
Implemented in 1.0.10
