### ISSUE TITLE
add no-cache headers to each request to bypass caches

### ISSUE THREAD

**Issue by mieszkomalawski** [opengs/uashield#51]

**Comment by Razikus** [comment]
Maybe we should add random indicator for no-cache, cause it would be indicator for potential defender, that he should block specified combo of user-agent and so on

**Comment by sunflowerdawn** [comment]
New to this project and eager to help!

Seems to me you could randomly change up the header `Cache-Control` to any of the three `no-cache`, `no-store`, and `private`. Any of those should still bypass public shared caching (assuming the shared caches are obeying these headers and not just caching everything by default).

If that sounds like a good plan, happy to give this one a go at implementing.

**Comment by StVolodymyr** [comment]
it can be easy done after the PR https://github.com/opengs/uashield/pull/66 or inside. I'm going to add it to the PR

**Comment by forzaukraine** [comment]
Added to the PR https://github.com/opengs/uashield/pull/66
