### ISSUE TITLE
Proposal: switch to slow post attack if GET is not effective

### ISSUE THREAD

**Issue by mieszkomalawski** [opengs/uashield#56]
Slow POST attack might be more effective for some targets https://www.netscout.com/what-is-ddos/slow-post-attacks

**Comment by forzaukraine** [comment]
this modification will probably require some refacroring for the the tagrest file format so we'll be able to use something like this
```
{
"page": "https://www.sberbank.ru/",
"attack": "slow_post",
},
{
"page": "https://www.sberbank.ru/",
"attack": "default",
},
...
```

**Comment by opengs** [comment]
Slow post attack is supported in 0.0.31. Slowloris attack was added to the list of possible attack types.
