### ISSUE TITLE
Proposal : Show links to download, for easy access to new versions

### ISSUE THREAD

**Issue by RasmusOtharKirketerp** [opengs/uashield#58]
Maybe even some code that can validate for new version availiable?

**Comment by Amet13** [comment]
Hey.
There is a badge link to the latest release.
You can find it on README.

<img width="993" alt="Screenshot 2022-03-02 at 22 24 46" src="https://user-images.githubusercontent.com/5184847/156455858-ef9df536-8257-422d-936d-e5c264d59ad4.png">

**Comment by Razikus** [comment]
Autoupdater would be also in 0.0.10 probably

**Comment by Razikus** [comment]
Autoupdater introtuced
