### ISSUE TITLE
Proposal : Show current status on current target (down/up)

### ISSUE THREAD

**Issue by RasmusOtharKirketerp** [opengs/uashield#59]
Good point. What about a status just showing it attackpoint is available then? So user mayby can switch VPN? Maybe a rolling status for how many procent is reachable og those URLs currently under attack?

**Comment by Razikus** [comment]
Can you provide more details? 
Hard to say if target is down or it just banned proxy

**Comment by RasmusOtharKirketerp** [comment]
Good point. What about a status just showing it attackpoint is available then? So user mayby can switch VPN? Maybe a rolling status for how many procent is reachable og those URLs currently under attack?

**Comment by Razikus** [comment]
we have to consider about some improvement on this

**Comment by Razikus** [comment]
Related #90

**Comment by opengs** [comment]
Please use the official statistics and status page https://itarmy.com.ua/check/ . We are fully integrated with IT Army. This page has advanced methods to determinate status of the server
