### ISSUE TITLE
Docker version

### ISSUE THREAD

**Issue by pamidur** [opengs/uashield#6]
I have a quite some big channel plus I can use some aws resources.
For this docker image would be ideal

**Comment by lsheva** [comment]
Can work on this, the change should be trivial.

**Comment by pamidur** [comment]
would be nice to have threadcount/enableproxy options.
I plan to run them outside Ukraine

**Comment by sviatoslav-lebediev** [comment]
here is a headless version + docker https://github.com/sviatoslav-lebediev/uashield

```
docker run -it --init --rm   \
-e SITE_FILE="https://raw.githubusercontent.com/opengs/uashieldtargets/master/sites.json" \
-e PROXY_FILE="https://raw.githubusercontent.com/opengs/uashieldtargets/master/proxy.json" \
-e WORKERS_COUNT=50 moro/uashield-cli:latest
```

**Comment by constantin-ukr** [comment]
docker run -it --init --rm  -e SITE_FILE="https://raw.githubusercontent.com/opengs/uashieldtargets/master/sites.json" -e PROXY_FILE="https://raw.githubusercontent.com/opengs/uashieldtargets/master/proxy.json" -e WORKERS_COUNT=50 moro/uashield-cli:latest

**Comment by constantin-ukr** [comment]
clone or download repository. It is better cloning. We will be able to use updates faster and suit!
Win+R "cmd"
cd /D "path to the folder with Dockerfile"
docker build -t uashield .

**Comment by sviatoslav-lebediev** [comment]
I've synced https://github.com/sviatoslav-lebediev/uashield-cli with last changes + updated `moro/uashield-cli:latest` image you can pass `-e NON_VERBOSE_ERROR=true` and the output will be less noisy.

`
docker run -it --init --rm -e SITE_FILE="https://raw.githubusercontent.com/opengs/uashieldtargets/master/sites.json" -e PROXY_FILE="https://raw.githubusercontent.com/opengs/uashieldtargets/master/proxy.json" -e NON_VERBOSE_ERROR=true -e WORKERS_COUNT=50 moro/uashield-cli:latest
`

**Comment by Razikus** [comment]
Hmm docker version is now available here
https://github.com/opengs/uashield/pkgs/container/uashield
Sorry @sviatoslav-lebediev i didn't checked that you already made amazon work :(
maybe we can somehow use something from your project?
im preety sure that we can improve headless version

**Comment by sviatoslav-lebediev** [comment]
@Razikus yep, it would be great to have just one repo instead of 2
I've created a PR https://github.com/opengs/uashield/pull/57, it reduces a docker image in  4 times :)
As you could see my version supports custom SITE_FILE/PROXY_FILE/NON_VERBOSE_ERROR env variables. if you want I can create a PR for these features.

**Comment by opengs** [comment]
Docker version in 0.0.9 release
