### ISSUE TITLE
Про ваш проект

### ISSUE THREAD

**Issue by vitaleg** [opengs/uashield#60]
Хлопці, я розумію вашу мотивацію і поділяю ваші почуття щодо того, що відбувається, але якщо ви хоч трохи розумієте, як працюють телекомунікаційні мережі, то повинні розуміти, що те, чим ви займаєтеся, може вплинути на роботу мереж у самій Україні і через це може хтось постраждати або навіть втратити життя через те, що хтось з кимось не зможе зв'язатися в потрібний момент.

На русском:

Ребят, я понимаю вашу мотивацию и разделяю ваши чувства относительно происходящего, но если вы хоть немного понимаете как работают телекоммуникационные сеть, то должны понимать, что то, чем вы занимаетесь, может повлиять на работу сетей в самой Украине и из-за этого может кто-то пострадать или даже потерять жизнь из-за того, что кто-то с кем-то не сможет связаться в нужный момент.

**Comment by opengs** [comment]
Це так не працює. Ми спеціалізти в своїй області. Україну це ніяк не трогає.
