### ISSUE TITLE
Hi here is link (~200k websites) YP.com db (russian yellow pages for your botnet); Categorized

### ISSUE THREAD

**Issue by wsuphappyhour** [opengs/uashield#62]
Hi here is link to crawled YP.com (russian yellow pages for your botnet)
https://docs.google.com/spreadsheets/d/1LsXmPjUCc3v7hfXpJCgS7leQ_cWjKSjKUF1YDCxyzsc/edit#gid=1679811572

**Comment by opengs** [comment]
Websites are in use ))
