### ISSUE TITLE
Native Apple Silicon support

### ISSUE THREAD

**Issue by alex-titarenko** [opengs/uashield#63]
As or right now the build of MacOS supports only Inter processors.
Please make MacOS build as universal binary, so people can use it without Rossetta 2

**Comment by furiosae** [comment]
I was able to build the current v0.0.11 on an M1 Mac no problem, so it's certainly ready to go, and it runs exceptionally fast.

Problem is, [it seems that Quasar won't let you cross-compile both Intel and arm64 into a nice universal binary using their builder.](https://quasar.dev/quasar-cli/developing-electron-apps/configuring-electron#packager-vs-builder) (Looks like it might be possible with packager though.)

So for now, looks like the project here can either just offer two different downloads for each macOS target, or the project could adopt one more build process using [electron/universal](https://github.com/electron/universal), once both binaries are compiled. 

Either way, I'm happy to help with the manual cross-compiling on M1 until a more automated way is found.

@Razikus Let me know where I should upload the Apple arm64.dmg.

**Comment by furiosae** [comment]
Ok, didn't hear back from @Razikus (he's likely busy with more important matters!) so I posted a native M1 build on my forked repo. 

https://github.com/furiosae/uashield/releases/tag/v0.0.11

I know it's not as ideal as having it included here, but until a better way is made to build for both and bundle, this'll have to do.

**Comment by Razikus** [comment]
Sorry for late answer
The problem with the other name is that we can't support auto updating

Will arm64 version from linux also work on M1?

**Comment by furiosae** [comment]
> The problem with the other name is that we can't support auto updating

Not sure I follow. I'm happy to rename mine to whatever, or manually build a universal macOS (Intel and arm64) Electron app if that's easier. Just let me know.
 
> Will arm64 version from linux also work on M1?

To my knowledge, no.

**Comment by Razikus** [comment]
Like we discuss on Discord
From 0.0.13 it will be released automaticaly
