### ISSUE TITLE
Build Raspberry Pi AppIMage (Linux ARM)

### ISSUE THREAD

**Issue by TuxIoannes** [opengs/uashield#65]
People have Pis lying around without use - please build Linux ARM version of AppImage so we can easily run it on them.

**Comment by Razikus** [comment]
Hmm i must check if electron have cross compile feature
for now you can deploy it on Balena 

https://github.com/opengs/uashield#deploy-attacker-on-your-raspberry-pi

**Comment by Razikus** [comment]
Binary provided
