### ISSUE TITLE
Add guide how to create free VMs

### ISSUE THREAD

**Issue by OleksandrChekmez** [opengs/uashield#67]
You can add a guide like this (https://dou.ua/forums/topic/36795/) how to create free VMs and use them.
Please note that the guide above proposes an expensive VM, I think Standard B2s (2 vcpus, 4 GiB memory) is enough.

Recommend how many threads to set.

Few other tips:
1.  create VMs in different regions
2. After Vm is configured and app launched, it make sence to close RDP port on Networking tab of Azure VM portal

**Comment by denysbutenko** [comment]
Yes, that's a good tutorial. I have run tens of VMs (Linux) on Azure and manage it via [`tools/ansible/README.md`](https://github.com/opengs/uashield/blob/579ec12a7176ee148b34c3e5b525925c98b48026/tools/ansible/README.md#L3)

I'm working on a PR to add extra steps on how to use `*.pem` keys for azure VMs. It makes the management of dozens VMs as simple as possible via one command.

**Comment by OleksandrChekmez** [comment]
One more idea for VMs - configure automatic shutdown and startup with new IP to avoid possible IP blocks. 
I know there is a possibility to autoshutdown, but can`t find how to make auto start.

**Comment by denysbutenko** [comment]
@OleksandrChekmez added a guide to ansible README.md - https://github.com/opengs/uashield/blob/master/tools/ansible/README.md

**Comment by OleksandrChekmez** [comment]
I think it makes sense to move/copy this guide to https://github.com/opengs/uashield/tree/master/tools/azure because it's more about usage of [azure-custom-data-script.sh](https://github.com/opengs/uashield/blob/master/tools/azure/azure-custom-data-script.sh) and add list on it on main readme.md

Few possible notes for the guide:
 - If Azure says that there are no available size, click See all sizes and set filter to vCPUs=2, RAM=4-8GB and select cheapest:
![size_select](https://user-images.githubusercontent.com/17407089/156767974-ded80494-c848-4575-87f2-b17646d9836c.png)
 - VM cost affected by Disk type, its recommended to change default Premium SDD to Standard SDD (on Disks tab), to save cost and have VM for longer time.
 - Create VMs in different regions, if no available size in the selected. Some regions are much more expensive.

**Comment by vtinkerer** [comment]
I have a guide https://docs.google.com/document/d/11dV32WBAhKqH3fIYTczG0pTlX_3EdLkXoLAqY5z4UDo/edit?usp=sharing
Where should I place it?
Guys in Discord channel said that they don't want to use any external links.

**Comment by OleksandrChekmez** [comment]
@vtinkerer readme.md in tools/azure is the best option, see https://word2md.com/ to speed up conversion

**Comment by denysbutenko** [comment]
If you could please convert it to GitHub Markdown format it would be nice to have it.

**Comment by vtinkerer** [comment]
Is it possible to paste pictures with Markdown?
@denysbutenko

**Comment by OleksandrChekmez** [comment]
https://www.digitalocean.com/community/tutorials/markdown-markdown-images

**Comment by OleksandrChekmez** [comment]
images can be placed in subfolder

**Comment by opengs** [comment]
Documentation was added and then removed from GitHub (because of GitHub terms of use). This documentation moved here https://help-ukraine-win.com.ua/help-ukraine-win-ua/3 . English: https://help-ukraine-win.com.ua/help-ukraine-win-en/using-cloud-server
