### ISSUE TITLE
Add command line params for Windows version to enable/disable proxy and number of threads

### ISSUE THREAD

**Issue by OleksandrChekmez** [opengs/uashield#68]
Add command line params for Windows version to enable/disable proxy and number of threads,

It will help to automate VMs reboots and app start

**Comment by Razikus** [comment]
there is a headless version
are you using docker?

**Comment by OleksandrChekmez** [comment]
No, I'm asking about simple Windows app. Many users use it.

**Comment by opengs** [comment]
Done in 0.0.31 
![image](https://user-images.githubusercontent.com/34212339/162606803-a589a790-3302-48e3-a604-7c5818af3cba.png)
