### ISSUE TITLE
Increase ThreadCount options in GUI

### ISSUE THREAD

**Issue by pamidur** [opengs/uashield#7]
256 is a rookie number.
It only fries my CPU upto 15% and uses only ~70 out of ~300 mbps of channel

**Comment by Razikus** [comment]
Hey, now you can probably specify number of workers or user headless version
We releaseed 0.0.9 today

**Comment by RasmusOtharKirketerp** [comment]
Just installed 009 version, can still choose up to 256. This number should be like 1024 at least on my PC :)

**Comment by Razikus** [comment]
You can not use the slider but manually put number of threads
