### ISSUE TITLE
Додайте до логу timestamp  щоб бачити час відпрацювання/Add to log timestamp to see time of connection

### ISSUE THREAD

**Issue by gidiyan** [opengs/uashield#85]
Для того, щоб можна було зрозуміти коли останнє вдале з'єднання відболуся та чи потрібно змінювати ВПН(Через ВПН з відключеним проксі кількість успішних з'єднань вище при правильному виборі ВПН).скіншот свого лога додаю
It's necessary to see the time of last good connection and if it's time to switch VPN (number of connections with good VPN  and proxy off is higher). SS of current log added 
![image](https://user-images.githubusercontent.com/70430920/156629628-9c69b68b-d864-4cf5-b8b8-d307f52c7f83.png)

**Comment by Razikus** [comment]
What means for you "time of last good connection"
Request with response status 200?

**Comment by denysbutenko** [comment]
I think he means to add a timestamp of the request. So, we could filter logs using command-line tools to get feedback from the running systems.

**Comment by Razikus** [comment]
Are you using docker?
You can just make ```docker logs containerid/name -f -t ```

**Comment by denysbutenko** [comment]
Yeah, that's it. Thanks for the tip!

**Comment by gidiyan** [comment]
> What means for you "time of last good connection" Request with response status 200?

yep. i can look at logs of the container. instead i run in couple terminals containers and monitor if they have 200 respond. and beside docker in app(not headless) you have status ath the bottom. and would be good that time of any request(200 or other) would be shown by default or there would be an option to turn it in.
Thanks

**Comment by Razikus** [comment]
Ok, will implement something

**Comment by gidiyan** [comment]
for now for bash made simple script to collect and display  response status 200. maybe someone wonna use it

#!/bin/bash
docker ps -q > containers.id
while read container
        do
                docker logs -t -f $container | grep --color -P " 200"
done < containers.id

**Comment by sepo274** [comment]
[PR](https://github.com/opengs/uashield/pull/115) for the issue

**Comment by opengs** [comment]
Added
