### ISSUE TITLE
Build on Linux Mint 20.3 Cinnamon

### ISSUE THREAD

**Issue by iso4free** [opengs/uashield#87]
Не збирається з сирців в Linux Mint 20.3 Cinnamon - при виконанні команди npm install виникає наступна помилка:
`[ .................] \ fetchMetadata: sill fetchPackageMetaData error for @types/node@^12.20.21 Unexpected end of JSON input while parsing near '...zUgiVy+PSGAII7ZxndZZ`

**Comment by Razikus** [comment]
Node version?
It should work, use prebuild binaries if needed

**Comment by iso4free** [comment]
I have older version node, after update all fine, thanks.
