### ISSUE TITLE
Дати змогу коннектитись до ботнету без графічного кліента

### ISSUE THREAD

**Issue by DrJackilD** [opengs/uashield#9]
Я хочу використовувати VPSки задля скоординованих атак, але як я зараз розумію, є тільки електрон кліент для коннекту до ботнету. Я и мої коллеги можемо створити якийсь варіант без UI, на пітоні, але тоді мені треба скоординуватися с кимось хто може розповісти про внутрішню кухню

**Comment by xander-monk** [comment]
внутрішня кухня тут - 
https://github.com/opengs/uashield/blob/master/src-worker/doser.ts

**Comment by sviatoslav-lebediev** [comment]
https://github.com/sviatoslav-lebediev/uashield
якраз версія без ui, `npm run start:cli`

**Comment by DrJackilD** [comment]
@sviatoslav-lebediev так це ж те що треба!

**Comment by DrJackilD** [comment]
Залишилось у докер це все запхати и буде кльово. Зараз зробимо. @sviatoslav-lebediev а CLI версія тіки у твому форку?

**Comment by sviatoslav-lebediev** [comment]
напевно, я то собі робив для aws
тільки що додав можливість ставити кількість воркерів
`WORKERS_COUNT=100 npm run start:cli`

**Comment by sviatoslav-lebediev** [comment]
можу зробити докер

**Comment by DrJackilD** [comment]
а як ти на авс розгортав? лямбду, чи щось інше? може я и без докера зроблю тоді теж

**Comment by sviatoslav-lebediev** [comment]
я просто зробив інстанс, 
```
sudo yum install git
git clone ...
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
nvm use 16
npm install
npm run start:cli
```
потім створив image,потім вибрав його і сказав запустити інстанси 8 штук, і все, всі 8 штук вже з проставленою апкою, нодою і тд


![image](https://user-images.githubusercontent.com/19693768/156228417-28a69e99-945a-44d4-a078-7cd7df9920df.png)

**Comment by DrJackilD** [comment]
Дуже добре, дякую. Є два прохання:
1. Злити свої ченжи у головний репозіторій, щоб був один source of truth
2. Дати можливість передавати лист зі своїми проксями. Тому що коли відкритий лист юзає півкраїни - вони протухають дуже швидко. Я коли запускав UI тулзу - 95 відсотків реквестів фейлились. А так я б собі купив би на тиждень 25 проксі того хуйлостану - якраз до перемоги б вистачило

**Comment by DrJackilD** [comment]
Я б зробив то сам, але JS/TS - це ну зовсім не моє. Зробить зроблю, але воно займе у мене купу часу

**Comment by sviatoslav-lebediev** [comment]
@DrJackilD я створив репу виключно для cli, https://github.com/sviatoslav-lebediev/uashield-cli, все так само але можна запустити з env змінними `SITE_FILE=sites.json PROXY_FILE=proxies.json npm run start:cli`. спробуй, якщо це те що потрібно то я спробую додати це в офіційну ui версію.
p.s.  формати файлів повинні бути такі як в стандартній версії
https://raw.githubusercontent.com/opengs/uashieldtargets/master/sites.json
https://raw.githubusercontent.com/opengs/uashieldtargets/master/proxy.json

**Comment by sviatoslav-lebediev** [comment]
з ui версії складніше зробити docker, бо там багато залежностей від електрону які потрібно ставити, але ми ними потім не користуємось

**Comment by sviatoslav-lebediev** [comment]
додав підтримку для http/https SITE_FILE/PROXY_FILE. тобто можна передати `PROXY_FILE=https://raw.githubusercontent.com/opengs/uashieldtargets/master/proxy.json npm run start:cli`

**Comment by DrJackilD** [comment]
Дуже дякую!

**Comment by opengs** [comment]
Повтор #6 Закриється разом з цією задачею

**Comment by vvadymv** [comment]
Зробіть ami image публічним - я зможу запустити autoscaling group на spot instances
![image](https://user-images.githubusercontent.com/38409513/156417551-e97c55fa-0b21-482a-be0a-51b64507c0dd.png)

**Comment by opengs** [comment]
Реалізовано. Є Docker є без GUI.
