### ISSUE TITLE
Transalations

### ISSUE THREAD

**Issue by opengs** [opengs/uashield#95]
Add new translations and icons

[LITHUANIAN.txt](https://github.com/opengs/uashield/files/8185351/LITHUANIAN.txt)
[DUTCH.txt](https://github.com/opengs/uashield/files/8185353/DUTCH.txt)
[CZECH.txt](https://github.com/opengs/uashield/files/8185354/CZECH.txt)
[GERMAN.txt](https://github.com/opengs/uashield/files/8185355/GERMAN.txt)
[SLOVAK.txt](https://github.com/opengs/uashield/files/8185356/SLOVAK.txt)

**Comment by opengs** [comment]
Also mention translators
Gernam: Kiki/Jenny
Slovak: modingnation
Czech: Tatranka  |  gadzo_dzandre
Dutch: suvalley
Lithuanian: nick

**Comment by nedjulius** [comment]
hey, I can help with this. can make a PR in the upcoming few hours.

**Comment by Razikus** [comment]
still waiting :(

**Comment by nedjulius** [comment]
@Razikus working on it right now. 👍

**Comment by nedjulius** [comment]
@Razikus added PR -> https://github.com/opengs/uashield/pull/107. Also, the flag icons should be fixed - currently, they look cropped (at least on Mac OS machine):

<img width="525" alt="Screen Shot 2022-03-04 at 17 52 42" src="https://user-images.githubusercontent.com/45975811/156852905-ee3a75df-bacb-4d82-8f41-b3c2b4da64ba.png">

<img width="525" alt="Screen Shot 2022-03-04 at 17 52 32" src="https://user-images.githubusercontent.com/45975811/156852912-1a423109-430f-4bb7-b2ae-e2d781447cdc.png">

**Comment by RasmusOtharKirketerp** [comment]
I can translate to Danish, but i do not know. Can i just get a .txt file to translate please? :)

**Comment by opengs** [comment]
@RasmusOtharKirketerp  Sory for late response :(. Of course you can add TXT here
